cable_target_test_config:
  chassis_ip: "10.10.10.10"
  username: "CablePerfOptimalTest"
  password: "xena"
  tcp_port: 22606
  log_filename: "cable_target_test.log"
  port_pair_list:
    - tx: "3/0"
      rx: "6/0"
  module_media: "QSFPDD800"
  port_speed: "1x800G"
  lane: 1
  delay_after_reset: 2
  prbs_test_config:
    polynomial: "PRBS31"
    duration: 10
  transceiver_init_config:
    amp_init: 0
    pre_init: 0
    post_init: 0
    target_prbs_ber: 1e-9
    delay_after_eq_write: 2
